# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b6e13778f5e9e04b373005c2f36588bb4302b59111482fc17c5db2f5b36f22f00c827021f5ec9e923d0a11915660e3f48f8af83f7c161017323eeed56d9d0e

test:
  secret_key_base: 81412e20c11e1df022d827697ec9b68f35e155dd28245eecf609e162a0b0b119fc41be9037c6b1f5af23953d84ddf01341bf870a245a2e3a261b281881225e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
